name: finance
channels:
  - conda-forge
dependencies:
  - python=3.11
  - polars
  - yfinance
  - isort
  - black
  - toml
  - joblib
  - pylatex
  - ipykernel
  - matplotlib
  - seaborn
  - pyarrow
  - rich
  - pip
  - pip:
    - -e .
