portfolio = [
    "T",
    "AAPL",
    "DLR",
    "O",
    "KRN.DE",
    "VEUR.AS",
    "BRK-B",
    "EQR",
    "JNJ",
    "UL",
    "SPY",
    "MMM",
    "BTI",
    "GOOD",
    "IBM",
    "LTC",
    "ORCC",
    "PLTR",
    "PG",
    "VZ",
    "ISPA.DE",
    "IQQ6.DE",
    "QYLD",
    "MPW",
]

candidates = [
    "BLK",
    "LTC",
    "ISPA.DE",
    "IQQ6.DE",
    "QYLD",
    "MPW",
    "ARCC",
    "RYLD",
]